### ISSUE TITLE
How to add array 

### ISSUE THREAD

**Issue by dleurs** [CommandersAct/AndroidV5#1]
Hello,
(Issue linked with https://github.com/CommandersAct/pods/issues/21)

Can you please tell me the fonction to add Array ?

With : 
- implementation 'com.tagcommander.lib:core:5.3.0' 
- implementation 'com.tagcommander.lib:ServerSide:5.3.1'

I see inside TCAdditionnalProperties :
```
    public void addAdditionalProperty(String key, String value) {
        this.additionalProperties.put(key, value);
    }

    public void addAdditionalProperty(String key, JSONObject value) {
        this.additionalProperties.put(key, value);
    }

    public void addAdditionalProperty(String key, Boolean value) {
        this.additionalProperties.put(key, value);
    }

    public void addAdditionalProperty(String key, BigDecimal value) {
        this.additionalProperties.put(key, value);
    }

    public void addAdditionalProperty(String key, Float value) {
        this.additionalProperties.put(key, value);
    }

    public void addAdditionalProperty(String key, Integer value) {
        this.additionalProperties.put(key, value);
    }
```
No array ?

**Comment by CommandersAct** [comment]
Indeed we forgot to change the version number of Core so the release didn't push the new function:

    public void addAdditionalProperty(String key, List value)

I will correct this today and you should soon see a Core 5.3.1

**Comment by CommandersAct** [comment]
Uploaded and should be available on maven during the next hour.
