### ISSUE TITLE
TCS.disableServerSide() not working

### ISSUE THREAD

**Issue by gabor-demko-viesure** [CommandersAct/AndroidV5#4]
After calling
`TCS.disableServerSide()`
then
`TCS.execute(TCCustomEvent("name"))`
the event seems to be still tracked.

Using
```
com.tagcommander.lib:ServerSide:5.4.2
com.tagcommander.lib:core:5.3.2
```

Even though the documentation says: "This will also ignore all calls to the SDK by your application so that nothing is treated anymore and you don't have to protect those calls manually."

**Comment by CommandersAct** [comment]
Can you please provide your TCS instance initialisation code ?
Are you passing `ETCConsentBehaviour.PB_ALWAYS_ENABLED` parameter to your instance constructor ?

**Comment by gabor-demko-viesure** [comment]
I just use this constructor:
`public TCServerSide(int siteID, String sourceKey, Context appContext)`
So It should be defaulting to `ETCConsentBehaviour.PB_DEFAULT_BEHAVIOUR`
(not using the consent module)

**Comment by gabor-demko-viesure** [comment]
May be my bad for using multiple instances of TCServerSide. Investigating (its problematic to test). Will keep ypu posted.

**Comment by gabor-demko-viesure** [comment]
OK, tested it out, the issue was creating multiple TCServerSide instances by accident.

Why I overlooked this issues was mainly because we were replacing FirebaseAnalytics with it, and FirebaseAnalytics does not let you create multiple instances as you have to use FilebaseAnalytics.getInstance().

Basically just a @Singleton annotation was missing from the dagger module where I instantiate it.

You may want to think about preventing souch issues through your API similarly how FirebaseAnalytics does, but It was basically my bad for creating multiple instances.
