### ISSUE TITLE
Wrong device language value in version 5.4.0

### ISSUE THREAD

**Issue by pyby** [CommandersAct/AndroidV5#5]
Following the iOS SDK issue https://github.com/CommandersAct/iOSV5/issues/9, the device `language` and device `region` has been added. Thank you. It's the expected values.

On Android SDK, same properties has been added but with the "app" context values, not the "device" context values.

- Set a device in `en-US`.
- Run an application with only `fr` language and region.

Current result:
- `context.device.language` = fr
- `context.device.region` = US

Expected result:
- `context.device.language` = en
- `context.device.region` = US

Could it be fixed for `context.device`?

Current Android SDK returns language value which looks for `context.app.language` property.

EDIT: issue description updated. and I found that same issue on iOS SDK after some tests again. https://github.com/CommandersAct/iOSV5/issues/11

**Comment by CommandersAct** [comment]
Noted ! We'll try to update this next week!

**Comment by CommandersAct** [comment]
It's gonna be a bit longer we're adding 2-3 other small fixes (on both plateforms)

**Comment by CommandersAct** [comment]
Should be fixed in 5.4.1 released this morning!

**Comment by Loic-Dumas** [comment]
Tested in my project, issue fixed. Thanks a lot for the fix.
