### ISSUE TITLE
Update scm information and project URL in the `pom.xml` file

### ISSUE THREAD

**Issue by MGaetan89** [CommandersAct/AndroidV5#6]
# Context

On [Maven Central](https://central.sonatype.com/artifact/com.tagcommander.lib/ServerSide), we can see that the `pom.xml` file for `ServerSide` points to the old repository:
```xml
<scm>
  <connection>scm:git:github.com/TagCommander/Android.git</connection>
  <developerConnection>scm:git:ssh://github.com/TagCommander/Android.git</developerConnection>
  <url>https://github.com/TagCommander/android/tree/main</url>
</scm>
```

Same for the project URL:
```xml
<url>https://github.com/TagCommander/android/</url>
```

> [!NOTE]
> This is probably also true for the other modules.

# Issue

This causes automatic tools, like Dependabot, to link update PRs to the wrong repository. Also, the lack of tags prevents it from including release notes in the PR description.
For example, you can check [this PR](https://github.com/SRGSSR/pillarbox-android/pull/562).

# Proposed solution

- Update the scm and project URL to point to https://github.com/CommandersAct/AndroidV5.
- Create a new tag for each release, containing the changes.

**Comment by MGaetan89** [comment]
I see that the newest version of `ServerSide` and `FirebaseDestination` use the new repository URL. I guess that the other artefacts will be updated in the same way with their next release?

**Comment by ahakimsaid** [comment]
hi @MGaetan89, 
yes, indeed, other artifacts will be updated in their next releases

**Comment by MGaetan89** [comment]
Thanks, I'm closing this issue then 🙂
