### ISSUE TITLE
[ServerSide] `NullPointerException` in `TCPredefinedVariables.updateVariablesForNewSession()` since v5.5.4

### ISSUE THREAD

**Issue by MGaetan89** [CommandersAct/AndroidV5#7]
# Details 

In v5.5.3, the `numberSessions` was retrieved via `getPropertyFromSharedPreferences(String)`, which returns a non-`null` `String`.
In v5.5.4, the `numberSessions` is retrieved via `getData(String)`, which returns a `null`-able `String`. However, `numberSessions` is used directly, without checking if it is `null` first:
```java
if (numberSessions.isEmpty()) {
```

![Screenshot 2024-06-12 at 11 16 52](https://github.com/CommandersAct/AndroidV5/assets/1009664/977148ca-1db4-43e8-947a-8e17374ed6f4)

# Log

```
Attempt to invoke virtual method 'boolean java.lang.String.isEmpty)' on a null object reference at com.tagcommander.lib.serverside.TCPredefinedVariables.updateVariablesForNewSession
(TCPredefinedVariables.java:644)
```

# Additional context

We have applications in production reporting this crash. We're reverting back to ServerSide 5.5.3 until it is fixed.

**Comment by CommandersAct** [comment]
Hello !
Thank you for sending us this issue. We'll modify this asap.

**Comment by ahakimsaid** [comment]
Hello ! 
The problem has been identified and corrected, it'll be available in the next release ASAP ! 
thanks

**Comment by MGaetan89** [comment]
I see that ServerSide has received a new [5.5.5 release](https://github.com/CommandersAct/AndroidV5/blob/master/TCServerSide/changelog_Android_ServerSide.md), with the following note:
> Small fix for an internal value NPE.

Is it related to this ticket?

**Comment by ahakimsaid** [comment]
Hi @MGaetan89 , 
yes indeed, fix included is related to this ticket, please upgrade your library to latest 5.5.5 release.

**Comment by MGaetan89** [comment]
Thanks for the fix!
